version: '3.7'
services:
    php:
        image: php:8.0-fpm
        container_name: prestigeRent
        volumes:
            - ./project:/var/www/html
        ports:
            - "9000:9000"

    mailer:
        image: schickling/mailcatcher
        ports: 
            - "1025:1025"
            - "1080:1080"

    database:
        image: postgres:13-alpine
        environment:
          POSTGRES_DB: ${POSTGRES_DB:-PrestigeRent}
      # You should definitely change the password in production
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
          POSTGRES_USER: ${POSTGRES_USER:-PrestigeRent}
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: prestige@rent.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - database

volumes:
  db-data:
